const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Audio,
		C3.Plugins.Button,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.Pin,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Behaviors.Fade,
		C3.Plugins.Mouse,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Keyboard.Cnds.OnKey
	];
};
self.C3_JsPropNameTable = [
	{FundinhoInicio: 0},
	{Áudio: 0},
	{BotaoIniciar: 0},
	{Botao: 0},
	{TextoDesenvolvido: 0},
	{Âncora: 0},
	{FundoFase1: 0},
	{Sólido: 0},
	{Chao: 0},
	{Atrelar: 0},
	{Animação: 0},
	{CentrarEm: 0},
	{Plataforma: 0},
	{RestritoAoLayout: 0},
	{Jogador: 0},
	{Teclado: 0},
	{Árvore: 0},
	{Senóide: 0},
	{MoedaPastor: 0},
	{MoedaPontos: 0},
	{Pontuacao: 0},
	{Buraco: 0},
	{PlataformaPedra: 0},
	{PlataformaFlutuante: 0},
	{Dinheiro: 0},
	{Caixa: 0},
	{Esmaecer: 0},
	{Explosao: 0},
	{BaconPontuacao: 0},
	{Vidas: 0},
	{MuitoDinheiro: 0},
	{Burnes: 0},
	{Trofeu: 0},
	{Planta: 0},
	{Direcao: 0},
	{Inimigo: 0},
	{Marcador: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Texto: 0},
	{Texto2: 0},
	{Mouse: 0}
];

self.InstanceType = {
	FundinhoInicio: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	BotaoIniciar: class extends self.ISpriteInstance {},
	Botao: class extends self.IButtonInstance {},
	TextoDesenvolvido: class extends self.ITextInstance {},
	FundoFase1: class extends self.ISpriteInstance {},
	Chao: class extends self.ITiledBackgroundInstance {},
	Animação: class extends self.ISpriteInstance {},
	Jogador: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Árvore: class extends self.ISpriteInstance {},
	MoedaPastor: class extends self.ISpriteInstance {},
	MoedaPontos: class extends self.ISpriteInstance {},
	Pontuacao: class extends self.ITextInstance {},
	Buraco: class extends self.ISpriteInstance {},
	PlataformaPedra: class extends self.ISpriteInstance {},
	PlataformaFlutuante: class extends self.ISpriteInstance {},
	Dinheiro: class extends self.ISpriteInstance {},
	Caixa: class extends self.ISpriteInstance {},
	Explosao: class extends self.ISpriteInstance {},
	BaconPontuacao: class extends self.ISpriteInstance {},
	Vidas: class extends self.ITextInstance {},
	MuitoDinheiro: class extends self.ISpriteInstance {},
	Burnes: class extends self.ISpriteInstance {},
	Trofeu: class extends self.ISpriteInstance {},
	Planta: class extends self.ISpriteInstance {},
	Inimigo: class extends self.ISpriteInstance {},
	Marcador: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Texto2: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {}
}